version: 2.1
jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Hello world"
      - run: echo $DOCKERHUB_PASSWORD
workflows:
  my-workflow:
    jobs:
      - hello-job
          context: hi-circleci
